# Generated by Django 5.0.7 on 2024-07-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_message_chat_room_remove_message_sender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupchatroom",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
